// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/lexer.flex

package com.olc1;

import java.util.ArrayList;
import java.util.List;

// Importaciones necesarias
import java_cup.runtime.Symbol;

import com.olc1.reports.GoLiteError;
import com.olc1.reports.TokenEntry;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\4\23\1\24"+
    "\1\23\1\25\3\23\1\26\1\27\1\30\1\31\1\32"+
    "\2\0\1\33\4\34\1\35\2\34\1\36\1\37\4\34"+
    "\1\40\1\41\3\34\1\42\6\34\1\43\1\44\1\45"+
    "\1\0\1\34\1\0\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\34\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\1\34\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\74\1\34\1\75\1\76\1\77"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\15\23\1\26\1\1\1\27\1\30\1\0\1\31\1\0"+
    "\1\32\2\0\1\33\1\34\1\35\1\36\1\0\1\37"+
    "\1\0\1\40\1\41\1\42\1\43\14\23\1\44\13\23"+
    "\1\45\1\46\1\0\1\47\12\23\1\50\1\23\1\51"+
    "\1\52\1\53\10\23\1\54\1\55\1\23\1\56\1\23"+
    "\1\57\2\23\1\60\2\23\1\0\1\61\2\23\1\62"+
    "\5\23\1\63\1\64\1\23\1\65\2\23\1\66\1\23"+
    "\1\0\7\23\1\67\3\23\1\0\1\23\1\70\2\23"+
    "\1\71\1\72\1\73\1\23\1\74\1\75\1\0\1\23"+
    "\1\0\2\23\1\76\21\0\1\77\6\0\1\100\1\101"+
    "\1\0\1\102\2\0\1\103\4\0\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\100\0\u0140\0\u0180"+
    "\0\100\0\100\0\100\0\u01c0\0\100\0\u0200\0\100\0\u0240"+
    "\0\u0280\0\u02c0\0\100\0\u0300\0\u0340\0\u0380\0\u03c0\0\100"+
    "\0\100\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580"+
    "\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\100\0\u0740"+
    "\0\100\0\100\0\u0100\0\100\0\u0780\0\100\0\u07c0\0\u0800"+
    "\0\100\0\100\0\100\0\100\0\u0840\0\u0880\0\u08c0\0\100"+
    "\0\100\0\100\0\100\0\u0900\0\u0940\0\u0980\0\u09c0\0\u0a00"+
    "\0\u0a40\0\u0a80\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u03c0"+
    "\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0d00\0\u0d40\0\u0d80\0\u0dc0"+
    "\0\u0e00\0\u0e40\0\u0e80\0\100\0\100\0\u0ec0\0\u08c0\0\u0f00"+
    "\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080\0\u10c0\0\u1100"+
    "\0\u1140\0\u03c0\0\u1180\0\u03c0\0\u03c0\0\u03c0\0\u11c0\0\u1200"+
    "\0\u1240\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u03c0\0\100"+
    "\0\u13c0\0\u03c0\0\u1400\0\u03c0\0\u1440\0\u1480\0\u03c0\0\u14c0"+
    "\0\u1500\0\u1540\0\u03c0\0\u1580\0\u15c0\0\u03c0\0\u1600\0\u1640"+
    "\0\u1680\0\u16c0\0\u1700\0\u03c0\0\u03c0\0\u1740\0\u03c0\0\u1780"+
    "\0\u17c0\0\u03c0\0\u1800\0\u1840\0\u1880\0\u18c0\0\u1900\0\u1940"+
    "\0\u1980\0\u19c0\0\u1a00\0\u03c0\0\u1a40\0\u1a80\0\u1ac0\0\u1b00"+
    "\0\u1b40\0\u03c0\0\u1b80\0\u1bc0\0\u1c00\0\u03c0\0\u03c0\0\u1c40"+
    "\0\u03c0\0\u03c0\0\u1c80\0\u1cc0\0\u1d00\0\u1d40\0\u1d80\0\u03c0"+
    "\0\u1dc0\0\u1e00\0\u1e40\0\u1e80\0\u1ec0\0\u1f00\0\u1f40\0\u1f80"+
    "\0\u1fc0\0\u2000\0\u2040\0\u2080\0\u20c0\0\u2100\0\u2140\0\u2180"+
    "\0\u21c0\0\100\0\u2200\0\u2240\0\u2280\0\u22c0\0\u2300\0\u2340"+
    "\0\100\0\100\0\u2380\0\100\0\u23c0\0\u2400\0\100\0\u2440"+
    "\0\u2480\0\u24c0\0\u2500\0\100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\3\21\1\22\1\23\1\24\1\25\1\26\10\27"+
    "\1\30\1\2\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\27\1\40\1\27\1\41\1\27\1\42\2\27"+
    "\1\43\1\44\1\45\1\27\1\46\3\27\1\47\1\50"+
    "\1\51\101\0\2\3\1\0\2\3\123\0\1\52\46\0"+
    "\2\53\1\0\2\53\1\0\1\53\1\54\34\53\1\55"+
    "\33\53\11\0\1\56\66\0\2\57\1\0\2\57\1\0"+
    "\4\57\1\0\31\57\1\60\33\57\16\0\1\61\12\0"+
    "\1\62\66\0\1\63\10\0\1\64\63\0\1\65\4\0"+
    "\1\66\76\0\1\67\1\0\3\21\103\0\1\70\77\0"+
    "\1\71\77\0\1\72\77\0\1\73\71\0\3\27\5\0"+
    "\10\27\3\0\27\27\26\0\3\27\5\0\10\27\3\0"+
    "\16\27\1\74\10\27\26\0\3\27\5\0\10\27\3\0"+
    "\15\27\1\75\1\27\1\76\7\27\26\0\3\27\5\0"+
    "\10\27\3\0\1\77\14\27\1\100\11\27\26\0\3\27"+
    "\5\0\10\27\3\0\4\27\1\101\22\27\26\0\3\27"+
    "\5\0\10\27\3\0\12\27\1\102\14\27\26\0\3\27"+
    "\5\0\10\27\3\0\1\103\11\27\1\104\1\105\1\27"+
    "\1\106\4\27\1\107\4\27\26\0\3\27\5\0\10\27"+
    "\3\0\5\27\1\110\6\27\1\111\12\27\26\0\3\27"+
    "\5\0\10\27\3\0\4\27\1\112\22\27\26\0\3\27"+
    "\5\0\10\27\3\0\10\27\1\113\16\27\26\0\3\27"+
    "\5\0\10\27\3\0\4\27\1\114\15\27\1\115\4\27"+
    "\26\0\3\27\5\0\10\27\3\0\12\27\1\116\6\27"+
    "\1\117\2\27\1\120\2\27\26\0\3\27\5\0\10\27"+
    "\3\0\17\27\1\121\6\27\1\122\26\0\3\27\5\0"+
    "\10\27\3\0\1\123\26\27\101\0\1\124\10\0\1\53"+
    "\34\0\1\53\15\0\1\53\2\0\1\53\1\0\1\53"+
    "\22\0\1\125\65\0\2\57\4\0\72\57\15\65\1\126"+
    "\62\65\2\66\1\0\75\66\23\0\3\127\75\0\3\27"+
    "\5\0\10\27\3\0\16\27\1\130\10\27\26\0\3\27"+
    "\5\0\10\27\3\0\15\27\1\131\11\27\26\0\3\27"+
    "\5\0\10\27\3\0\4\27\1\132\22\27\26\0\3\27"+
    "\5\0\10\27\3\0\20\27\1\133\6\27\26\0\3\27"+
    "\5\0\10\27\3\0\14\27\1\134\12\27\26\0\3\27"+
    "\5\0\10\27\3\0\5\27\1\135\21\27\26\0\3\27"+
    "\5\0\10\27\3\0\20\27\1\136\6\27\26\0\3\27"+
    "\5\0\10\27\3\0\12\27\1\137\14\27\26\0\3\27"+
    "\5\0\10\27\3\0\15\27\1\140\11\27\26\0\3\27"+
    "\5\0\10\27\3\0\21\27\1\141\5\27\26\0\3\27"+
    "\5\0\10\27\3\0\17\27\1\142\7\27\26\0\3\27"+
    "\5\0\10\27\3\0\14\27\1\143\12\27\26\0\3\27"+
    "\5\0\10\27\3\0\21\27\1\144\5\27\26\0\3\27"+
    "\5\0\10\27\3\0\14\27\1\145\12\27\26\0\3\27"+
    "\5\0\10\27\3\0\12\27\1\146\14\27\26\0\3\27"+
    "\5\0\10\27\3\0\5\27\1\147\13\27\1\150\5\27"+
    "\26\0\3\27\5\0\10\27\3\0\14\27\1\151\12\27"+
    "\26\0\3\27\5\0\10\27\3\0\10\27\1\152\16\27"+
    "\26\0\3\27\5\0\10\27\3\0\17\27\1\153\7\27"+
    "\26\0\3\27\5\0\10\27\3\0\10\27\1\154\16\27"+
    "\26\0\3\27\5\0\10\27\3\0\22\27\1\155\4\27"+
    "\26\0\3\27\5\0\10\27\3\0\16\27\1\156\10\27"+
    "\26\0\3\27\5\0\10\27\3\0\17\27\1\157\7\27"+
    "\3\0\15\65\1\126\4\65\1\160\55\65\23\0\3\27"+
    "\5\0\10\27\3\0\4\27\1\161\22\27\26\0\3\27"+
    "\5\0\10\27\3\0\12\27\1\162\14\27\26\0\3\27"+
    "\5\0\10\27\3\0\1\163\26\27\26\0\3\27\5\0"+
    "\10\27\3\0\4\27\1\164\22\27\26\0\3\27\5\0"+
    "\10\27\3\0\21\27\1\165\5\27\26\0\3\27\5\0"+
    "\10\27\3\0\1\166\26\27\26\0\3\27\5\0\10\27"+
    "\3\0\4\27\1\167\22\27\26\0\3\27\5\0\10\27"+
    "\3\0\20\27\1\170\6\27\26\0\3\27\5\0\10\27"+
    "\3\0\1\171\26\27\24\0\1\172\1\0\3\27\5\0"+
    "\10\27\3\0\27\27\26\0\3\27\5\0\10\27\3\0"+
    "\2\27\1\173\24\27\26\0\3\27\5\0\10\27\3\0"+
    "\12\27\1\174\14\27\26\0\3\27\5\0\10\27\3\0"+
    "\22\27\1\175\4\27\26\0\3\27\5\0\10\27\3\0"+
    "\4\27\1\176\22\27\26\0\3\27\5\0\10\27\3\0"+
    "\2\27\1\177\24\27\26\0\3\27\5\0\10\27\3\0"+
    "\2\27\1\200\5\27\1\201\11\27\1\202\4\27\26\0"+
    "\3\27\5\0\10\27\3\0\21\27\1\203\5\27\26\0"+
    "\3\27\5\0\10\27\3\0\4\27\1\204\22\27\26\0"+
    "\3\27\5\0\10\27\3\0\4\27\1\205\22\27\26\0"+
    "\3\27\5\0\10\27\3\0\14\27\1\206\12\27\26\0"+
    "\3\27\5\0\10\27\3\0\11\27\1\207\15\27\26\0"+
    "\3\27\5\0\10\27\3\0\10\27\1\210\16\27\26\0"+
    "\3\27\5\0\10\27\3\0\22\27\1\211\4\27\26\0"+
    "\3\27\5\0\10\27\3\0\4\27\1\212\22\27\26\0"+
    "\3\27\5\0\10\27\3\0\21\27\1\213\5\27\44\0"+
    "\1\214\61\0\3\27\5\0\10\27\3\0\4\27\1\215"+
    "\22\27\26\0\3\27\5\0\10\27\3\0\17\27\1\216"+
    "\7\27\26\0\3\27\5\0\10\27\3\0\4\27\1\217"+
    "\22\27\26\0\3\27\5\0\10\27\3\0\15\27\1\220"+
    "\11\27\26\0\3\27\5\0\10\27\3\0\14\27\1\221"+
    "\12\27\26\0\3\27\5\0\10\27\3\0\2\27\1\222"+
    "\24\27\26\0\3\27\5\0\10\27\3\0\2\27\1\223"+
    "\24\27\26\0\3\27\5\0\10\27\3\0\3\27\1\224"+
    "\23\27\26\0\3\27\5\0\10\27\3\0\14\27\1\225"+
    "\12\27\26\0\3\27\5\0\10\27\3\0\12\27\1\226"+
    "\14\27\26\0\2\27\1\227\5\0\10\27\3\0\27\27"+
    "\70\0\1\230\35\0\3\27\5\0\10\27\3\0\2\27"+
    "\1\231\24\27\26\0\3\27\5\0\10\27\3\0\14\27"+
    "\1\232\12\27\26\0\3\27\5\0\10\27\3\0\20\27"+
    "\1\233\6\27\26\0\3\27\5\0\10\27\3\0\14\27"+
    "\1\234\12\27\26\0\3\27\5\0\10\27\3\0\6\27"+
    "\1\235\20\27\26\0\3\27\5\0\10\27\3\0\21\27"+
    "\1\236\5\27\26\0\3\27\5\0\10\27\3\0\7\27"+
    "\1\237\17\27\26\0\3\27\5\0\10\27\3\0\22\27"+
    "\1\240\4\27\26\0\3\27\5\0\10\27\3\0\21\27"+
    "\1\241\5\27\26\0\1\27\1\242\1\27\5\0\10\27"+
    "\3\0\27\27\61\0\1\243\44\0\3\27\5\0\10\27"+
    "\3\0\21\27\1\244\5\27\24\0\1\245\1\0\3\27"+
    "\5\0\10\27\3\0\27\27\26\0\3\27\5\0\10\27"+
    "\3\0\23\27\1\246\3\27\26\0\3\27\5\0\10\27"+
    "\3\0\20\27\1\247\6\27\26\0\3\27\5\0\10\27"+
    "\3\0\4\27\1\250\22\27\65\0\1\251\36\0\1\252"+
    "\1\0\3\27\5\0\10\27\3\0\27\27\41\0\1\253"+
    "\62\0\1\254\1\0\3\27\5\0\10\27\3\0\27\27"+
    "\24\0\1\255\1\0\3\27\5\0\10\27\3\0\27\27"+
    "\72\0\1\256\52\0\1\257\117\0\1\260\50\0\1\261"+
    "\5\0\1\262\75\0\1\263\120\0\1\264\113\0\1\265"+
    "\54\0\1\266\115\0\1\267\56\0\1\270\114\0\1\271"+
    "\76\0\1\272\101\0\1\273\65\0\1\274\110\0\1\275"+
    "\101\0\1\276\70\0\1\277\73\0\1\300\120\0\1\301"+
    "\62\0\1\302\107\0\1\303\73\0\1\304\55\0\1\305"+
    "\111\0\1\306\100\0\1\307\61\0\1\310\122\0\1\311"+
    "\102\0\1\312\62\0\1\313\120\0\1\314\10\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9536];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\3\1\1\11\4\1\2\11\15\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\1\11\2\0\4\11"+
    "\1\0\1\1\1\0\4\11\30\1\2\11\1\0\31\1"+
    "\1\11\11\1\1\0\21\1\1\0\13\1\1\0\12\1"+
    "\1\0\1\1\1\0\3\1\21\0\1\11\6\0\2\11"+
    "\1\0\1\11\2\0\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // private Symbol symbol(int type) {
    //     return new Symbol(type, yyline, yycolumn);
    // }

    // private Symbol symbol(int type, Object value) {
    //     return new Symbol(type, yyline, yycolumn, value);
    // }

    public final List<GoLiteError> errors = new ArrayList<>();
    public final List<TokenEntry> tokens = new ArrayList<>();

    private Symbol track(int type, int line, int col, String text) {
        String typeName = (type >= 0 && type < sym.terminalNames.length)
            ? sym.terminalNames[type] : "UNKNOWN";
        tokens.add(new TokenEntry(typeName, text, line, col));
        return new Symbol(type, line, col, text);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return new Symbol(sym.EOF, yyline, yycolumn, yytext());
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errors.add(new GoLiteError("léxico", "Caracter no reconocido: " + yytext(), yyline, yycolumn));
            }
          // fall through
          case 69: break;
          case 2:
            { /* pass */
            }
          // fall through
          case 70: break;
          case 3:
            { return track(sym.not, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 4:
            { return track(sym.mod, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 5:
            { return track(sym.lparen, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 6:
            { return track(sym.rparen, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 7:
            { return track(sym.times, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 8:
            { return track(sym.plus, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 9:
            { return track(sym.comma, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 10:
            { return track(sym.minus, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 11:
            { return track(sym.dot, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 12:
            { return track(sym.slash, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 13:
            { return track(sym.integer, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 14:
            { return track(sym.colon, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 15:
            { return track(sym.scol, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 16:
            { return track(sym.lt, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 17:
            { return track(sym.assign, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 18:
            { return track(sym.gt, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 19:
            { return track(sym.id, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 20:
            { return track(sym.lbracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 21:
            { return track(sym.rbracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 22:
            { return track(sym.lbrace, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 23:
            { return track(sym.rbrace, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 24:
            { return track(sym.neq, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 25:
            { String raw = yytext(); tokens.add(new TokenEntry("string", raw.substring(1, raw.length() - 1), yyline, yycolumn)); return new Symbol(sym.string, yyline, yycolumn, raw.substring(1, raw.length() - 1));
            }
          // fall through
          case 93: break;
          case 26:
            { return track(sym.and, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 27:
            { return track(sym.plusplus, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 28:
            { return track(sym.plus_assign, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 29:
            { return track(sym.minusminus, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 30:
            { return track(sym.minus_assign, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 31:
            { /* Ignorar comentarios de una línea */
            }
          // fall through
          case 99: break;
          case 32:
            { return track(sym.walrus_assign, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 33:
            { return track(sym.leq, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 34:
            { return track(sym.eq, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 35:
            { return track(sym.geq, yyline, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 36:
            { return track(sym.kwIf,      yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          case 37:
            { return track(sym.or, yyline, yycolumn, yytext());
            }
          // fall through
          case 105: break;
          case 38:
            { return track(sym.rune, yyline, yycolumn, yytext());
            }
          // fall through
          case 106: break;
          case 39:
            { return track(sym.decimal, yyline, yycolumn, yytext());
            }
          // fall through
          case 107: break;
          case 40:
            { return track(sym.kwFor,      yyline, yycolumn, yytext());
            }
          // fall through
          case 108: break;
          case 41:
            { return track(sym.kwInt,     yyline, yycolumn, yytext());
            }
          // fall through
          case 109: break;
          case 42:
            { return track(sym.kwLen, yyline, yycolumn, yytext());
            }
          // fall through
          case 110: break;
          case 43:
            { return track(sym.kwNil,     yyline, yycolumn, yytext());
            }
          // fall through
          case 111: break;
          case 44:
            { return track(sym.kwVar,     yyline, yycolumn, yytext());
            }
          // fall through
          case 112: break;
          case 45:
            { /* Ignorar comentarios multilínea */
            }
          // fall through
          case 113: break;
          case 46:
            { return track(sym.kwBool,    yyline, yycolumn, yytext());
            }
          // fall through
          case 114: break;
          case 47:
            { return track(sym.kwCase,     yyline, yycolumn, yytext());
            }
          // fall through
          case 115: break;
          case 48:
            { return track(sym.kwElse,    yyline, yycolumn, yytext());
            }
          // fall through
          case 116: break;
          case 49:
            { return track(sym.kwFunc,    yyline, yycolumn, yytext());
            }
          // fall through
          case 117: break;
          case 50:
            { return track(sym.kwRune,    yyline, yycolumn, yytext());
            }
          // fall through
          case 118: break;
          case 51:
            { return track(sym.kwTrue,    yyline, yycolumn, yytext());
            }
          // fall through
          case 119: break;
          case 52:
            { return track(sym.kwType,     yyline, yycolumn, yytext());
            }
          // fall through
          case 120: break;
          case 53:
            { return track(sym.kwBreak,    yyline, yycolumn, yytext());
            }
          // fall through
          case 121: break;
          case 54:
            { return track(sym.kwFalse,   yyline, yycolumn, yytext());
            }
          // fall through
          case 122: break;
          case 55:
            { return track(sym.kwAppend,   yyline, yycolumn, yytext());
            }
          // fall through
          case 123: break;
          case 56:
            { return track(sym.kwReturn,   yyline, yycolumn, yytext());
            }
          // fall through
          case 124: break;
          case 57:
            { return track(sym.kwString,  yyline, yycolumn, yytext());
            }
          // fall through
          case 125: break;
          case 58:
            { return track(sym.kwStruct,   yyline, yycolumn, yytext());
            }
          // fall through
          case 126: break;
          case 59:
            { return track(sym.kwSwitch,   yyline, yycolumn, yytext());
            }
          // fall through
          case 127: break;
          case 60:
            { return track(sym.kwDefault,  yyline, yycolumn, yytext());
            }
          // fall through
          case 128: break;
          case 61:
            { return track(sym.kwFloat,   yyline, yycolumn, yytext());
            }
          // fall through
          case 129: break;
          case 62:
            { return track(sym.kwContinue, yyline, yycolumn, yytext());
            }
          // fall through
          case 130: break;
          case 63:
            { return track(sym.fmt_println, yyline, yycolumn, yytext());
            }
          // fall through
          case 131: break;
          case 64:
            { return track(sym.kwSlicesIndex, yyline, yycolumn, yytext());
            }
          // fall through
          case 132: break;
          case 65:
            { return track(sym.strconv_atoi, yyline, yycolumn, yytext());
            }
          // fall through
          case 133: break;
          case 66:
            { return track(sym.kwStringsJoin, yyline, yycolumn, yytext());
            }
          // fall through
          case 134: break;
          case 67:
            { return track(sym.reflect_typeof, yyline, yycolumn, yytext());
            }
          // fall through
          case 135: break;
          case 68:
            { return track(sym.strconv_parsefloat, yyline, yycolumn, yytext());
            }
          // fall through
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
